export const listApi = {
  LOGIN: 'auth/login',
  REGISTER: 'auth/register',
  CONFIRM_OTP: 'auth/active-user',
  SEND_OTP_FORGOT_PASSWORD: 'auth/send-otp-forgot-password',
  FORGOT_PASSWORD: 'auth/forgot-password',
  LIST_POST: 'posts/user-tourguide',
  POST_DETAIL: 'posts/user-tourguide',
  GET_COMMENT: 'comments',
  CREATE_POST: 'posts/user-tourguide',
  GET_POST_USER: 'posts/user',
  DELETE_POST_USER: 'posts/user',
};

export const routesName = {
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  ConfirmOtpScreen: 'ConfirmOtpScreen',
  HomeScreen: 'HomeScreen',
  ForgotPassword: 'ForgotPassword',
  TabHome: 'TabHome',
  PostDetailScreen: 'PostDetailScreen',
  CommentDetailScreen: 'CommentDetailScreen',
  TourDetailScreen: 'TourDetailScreen',
  TourScreen: 'TourScreen',
  CartScreen: 'CartScreen',
  CreatePostScreen: 'CreatePostScreen',
  ListPostUserScreen: 'ListPostUserScreen',
  EditPostScreen: 'EditPostScreen',
};
